name: CICD for Car Price Prediction A3

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout to project repository
      uses: actions/checkout@v3


    - name: Python environment setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.14'


    - name: Install dependencies for project
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute unit tests
      run: |
        pytest test/
  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout Project Repo
      uses: actions/checkout@v3

    - name: DockerHub Authentication
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Create Docker Deployment Image
      run: docker build -t kpzik/a3_price_prediction .

    - name: Push Image to DockerHub
      run: docker push kpzik/a3_price_prediction

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.MLBRAIN_HOST}}
          username: ${{ secrets.MLBRAIN_USER}}
          key: ${{ secrets.MLBRAIN_SSH_KEY }}
          proxy_host: ${{secrets.BAZOOKA_HOST}}
          proxy_username: ${{ secrets.BAZOOKA_USER }}
          proxy_key: ${{ secrets.BAZOOKA_SSH_KEY }}
          script: |
            docker pull kpzik/a3_price_prediction
            docker compose -f docker-compose-prod.yaml down --remove-orphans
            docker compose -f docker-compose-prod.yaml up -d
          debug: true   